hydromast_interface:
  ros__parameters:
    serial_params:
      port: "/dev/ttyUSB0"
      baud: 115200
      device_hwid: "0403:6001"
    incoming_message:
      header: "N03"
      footer: "/r/n"
      packet_size: 0
      rate_hz: 50
    publish_topic:
      name: "hydromast_data"
      frame_id: "n03"
