hydromast_n27_interface:
  ros__parameters:
    serial_params:
      use_port: True       # if use_port is False, device_hwid will be used to scan all ports
      port: "/dev/ttyS3"   # if port is fixed it should be used instead of device_hwid
      baud: 115200
      device_hwid: "0403:6001"
    incoming_message:
      header: "N27"
      footer: "/r/n"
      packet_size: 0
      rate_hz: 50
    publish_topic:
      name: "hydromast_n27_data"
      frame_id: "n27"
